version: '3'
services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./path/to/project:/var/www/laravel
      - ./images/nginx/vhost.conf:/etc/nginx/conf.d/laravel.conf
    working_dir:
      /var/www/laravel
    links:
      - php

  php:
    build: ./images/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./path/to/project:/var/www/laravel
    working_dir:
      /var/www/laravel
    links:
      - mysql

  mysql:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes:
      - data:/var/lib/data
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: secret

volumes:
  data: